### ISSUE TITLE
question/suggestion

### ISSUE THREAD

**Issue by stefanpenner** [toranb/ember-cli-simple-validation#1]
rather then defining `valid` lazily, why not just make it a CP on the mixin itself?
https://github.com/toranb/ember-cli-simple-validation/blob/master/addon/mixins/validate.js#L18-L24

**Comment by toranb** [comment]
I actually _wanted_ to do it this way but couldn't figure out how to define what properties to "listen for" without doing defineProperty like I did. Any pro tip to help me refactor this as you suggested :)

https://github.com/toranb/ember-cli-simple-validation/blob/master/addon/mixins/validate.js#L24

**Comment by stefanpenner** [comment]
add the property to the mixin itself

**Comment by toranb** [comment]
Right on but the part I linked to in particular - how can I tell that CP when it should break the cache (when each validation required is dynamic)?

**Comment by stefanpenner** [comment]
`this.notifyPropertyDidChange('valid')`

**Comment by toranb** [comment]
Ah nice! so in the validate attribute I would simply fire this.notifyPropertyDidChange("valid")

**Comment by toranb** [comment]
This was updated in the 0.2.0 release today - just one clarification (instead of notifyPropertyDidChange I did the below and it seemed to do the trick)

``` js
this.notifyPropertyChange("valid")
```

https://github.com/toranb/ember-cli-simple-validation/blob/e5dd6fc667988aedcd30bb87e82a7bd02d62dea3/addon/mixins/validate.js#L37
