### ISSUE TITLE
Manually add CSS

### ISSUE THREAD

**Issue by mike-post** [toranb/ember-cli-simple-validation#11]
I just added this to a new project and couldn't figure out why my validation errors were showing. I realized it's because I didn't have a definition for the CSS class "hidden".

I could have _sworn_ that the CSS used to be included. Regardless, if you need to add the CSS class yourself, it might be good to call out in the readme.

**Comment by toranb** [comment]
Agreed -if you don't add this class it's a painful experience. Sorry for not making that more clear but it is fairly clear (not hidden from the consumer).

<img width="764" alt="screen shot 2015-09-30 at 7 57 32 pm" src="https://cloud.githubusercontent.com/assets/147411/10210536/a1537396-67ad-11e5-966a-91cb40aabc53.png">
