### ISSUE TITLE
isDone property

### ISSUE THREAD

**Issue by snewcomer** [toranb/ember-cli-simple-validation#14]
Hey.  Just was wondering where this `isDone` property that is being observed on the model comes from.  Working with a different approach in regards to control flow, and at some point `self.get('model')` is undefined as we are removing the record on delete.  It's our app's problem, but was trying to learn why this observer was being fired.  Thanks for the help!

https://github.com/toranb/ember-cli-simple-validation/blob/master/addon/mixins/validate.js#L62

**Comment by snewcomer** [comment]
I'll close this.  Looks like the `isDone` property is called from a `removeObject` call.  And the error was the result of removing the object before the transition away from the detail route happened (result of transition only after promises have resolved).  Almost need to delete the object after the transition occurs, which feels a bit weird in order for simple-validation not to give me an error.

**Comment by toranb** [comment]
In this app I've got acceptance tests that show both adding/removing aren't an issue when using validateEach so it might be worth writing something like this to prove your setup is correct (or to help you dive deeper into what the actual error was and why it blew up)

https://github.com/toranb/ember-cli-simple-validation/blob/master/tests/acceptance/array-form-validation-test.js#L170

Here is the controller for the test above

https://github.com/toranb/ember-cli-simple-validation/blob/master/tests/dummy/app/controllers/multi.js#L13

**Comment by snewcomer** [comment]
@toranb yep I see this.  But what I don't think is that having validateEach will allow one to remove the model before transitioning away to the next route.  I could write a test for this tomorrow.
