### ISSUE TITLE
Message still showing on submit

### ISSUE THREAD

**Issue by rossjha** [toranb/ember-cli-simple-validation#15]
Hi, just trying out your addon and it's working well!  On submission the 'hidden' class is removed from the span.  Should this be reapplied?  On submission the field is empty and the message appears.  I'm also not sure where the following needs to go? 

```
Ember.Object.extend({
    email: null,
    emailIsPrimed: false,
    emailChanged: Ember.observer("email", function () {
        this.set("emailIsPrimed", true);
    })
});
```

**Comment by toranb** [comment]
Thanks for checking out the project! When you say "on submission" can you show the code block you are using? If I had to guess I'd say it looks something like this ...

``` js

export default Ember.Controller.extend(ValidationMixin, {
    nameValidation: validate("model.name"),
    actions: {
        save: function() {
            this.set("submitted", true);
            if(this.get("valid")) {
                //executed when all fields are valid
            }
        }
    }
});
```

If that is the case and the form is truly valid after the form validation logic runs I'd expect the "hidden" class is removed because the form is legit (truly valid for the user to move on / transition / etc).

About the object you showed - if you want the "isPrimed" behavior (meaning we don't alert the user of validation errors until after they start typing) you can add an observer to your ember-model / ember object (if you are using vanilla).

**Comment by nicwillemse** [comment]
Is there a way to put the hidden class back ?

**Comment by toranb** [comment]
Great question - it will add/remove the hidden class based on the validation rule you have in place. So in theory :) you make the input valid (meeting whatever rule you had in place) and the hidden attribute should return dynamically. In the example above - just having a name at all should add "hidden" back to the validation span

**Comment by nicwillemse** [comment]
Thanks @toranb so im facing an issue with this at the moment, when I enter invalid data, leave the route and come back to it (with a new model)the old validation message is still present. 

Is there anyway to get around this ?

**Comment by toranb** [comment]
@nicwillemse are you using an ember data model, simple store model or something?

**Comment by nicwillemse** [comment]
this is an ember data model atm

**Comment by toranb** [comment]
@nicwillemse with ember-data or vanilla ember object you will need to reset the "primed" value you are using to get that form back to the default state. Not something I stated explicitly in the readme (sorry) - but something like this should be what you want

```js
Ember.Object.extend({
    username: null,
    usernameIsPrimed: false,
    usernameChanged: Ember.observer("username", function () {
        this.set("usernameIsPrimed", true);
    }),
    init() {
        this._super(...arguments);
        this.set("usernameIsPrimed", false);
    }
});
```

**Comment by toranb** [comment]
@nicwillemse I just realized how wrong that solution was :) instead you will need to set `usernameIsPrimed` from the setupController method in your route (assuming you "re-enter" the form from a route like this). The root problem is that primed value - my sister project `ember-cli-simple-store` will reset this for you (built into the attr) but in your situation w/ ember-data you should just find a place you can reset it before loading up the controller/or component.

If that isn't clear and you have an example repo I can look at /or twiddle let me know
