### ISSUE TITLE
Reusable validation methods?

### ISSUE THREAD

**Issue by IntellectProductions** [toranb/ember-cli-simple-validation#16]
I know you can either pass a regex or function as the second parameter. I'm implementing min and max lengths, but I would just like to do `minlength: 3` or something of that sort.. And what if it has two extra validations? It has a min length, max length, AND must be numeric?

This library doesn't seem to allow that flexibility/re-usability. Am I just not seeing it?

**Comment by toranb** [comment]
We don't offer a baked in reuse strategy but I've used vanilla JS functions and an ember mixin to accomplish what you described. Let me know if you need a full blown example to better illustrate the approach.

**Comment by IntellectProductions** [comment]
Honestly, an example would be very much appreciated. I'm new to Emberjs (I typically use Vuejs with Laravel.. so I'm not a javascript expert, but I do know quite a bit of it). I'm VERY curious to see how you go about this since I'm all about re-usability!

**Comment by toranb** [comment]
Very cool - always glad to have new ember developers checkout the project! I'll throw together something after I'm off work tonight! thanks for opening the issue!

**Comment by IntellectProductions** [comment]
@toranb thank you very much!! :) I'm glad your project is still being worked on as well so that's always important :)

Also, what if a field isn't required, but need a minimum length of 4 if it's provided? I know `validate()` makes it required. Just curious if there is a way to validate without it being required.

**Comment by toranb** [comment]
I've added this to the test build as documentation for future readers :)

https://github.com/toranb/ember-cli-simple-validation/commit/b93b876fdd24d9ef78e1c35b20ec38c2cdc63e4c

If you don't want to look through the entire commit here is the quick rundown

1) create a file that holds vanilla functions you can use all over/ import from some random JS lib/etc

``` js
export var min = function(value) {
    return value && value.length > 3;
};
```

2) create a mixin that will be used in multiple places and import the function above :)

``` js
import Ember from "ember";
import { min } from "dummy/utils/funcs";
import { validate } from "ember-cli-simple-validation/mixins/validate";

export default Ember.Mixin.create({
    minValidation: validate("model.name", min)
});
```

3) add this mixin to your components/or controllers to validate the form

``` js
import Ember from "ember";
import MinMaxMixin from "dummy/mixins/min-max";
import { ValidationMixin } from "ember-cli-simple-validation/mixins/validate";

export default Ember.Controller.extend(ValidationMixin, MinMaxMixin, {
    actions: {
        save: function() {
            this.set("submitted", true);
            if(this.get("valid")) {
                this.transitionToRoute("success");
            }
        }
    }
});
```

any other questions let me know :)

**Comment by toranb** [comment]
To your question about validation w/out a hard requirement ... that would be a new feature for sure. You can almost do it manually in your save/submit like method today by looking through the validation(s) and excluding the one field you don't care about ... but it's not nice/pretty or easy I'll admit

It's possible this could be a future enhancement (something like required="true" by default but a way to opt out for special cases. Almost like the delayed flag today)
