### ISSUE TITLE
Grabbing errors

### ISSUE THREAD

**Issue by IntellectProductions** [toranb/ember-cli-simple-validation#17]
I'm following the documentation, but I'm not sure if `this.get('valid')` returns false.. how do I grab the errors that occurred? Right now, all I have is `There were errors in your form.` .. but that's not really helpful on the users part.

Thanks for any information,
Haley

**Comment by toranb** [comment]
A few questions to help me diagnose :)

1) what version of ember are you using?
2) what version of ember-cli (or is this on twiddle/jsbin) ?
3) is this using vanilla ember objects, ember-data or ember-cli-simple-store models (and what version)?
4) using components or controllers?
5) what does your form `js` and `hbs` look like? what does the bound model look like?

To answer w/out any context ...

1) `this.get('valid')` should return true / false or undefined across the board. 
2) The errors are tied to the bound component itself

``` js
{{#validation-error-field submitted=submitted className="red" field="name" model=model validation=nameValidation}}invalid name{{/validation-error-field}}
```

One thing that may be helpful to you also - pull down this repo and do the npm install/bower install work. Then if you do `ember s` from the root you can browse the test app and see it in action :)

This will let you browse the many different forms/ look at the source to see how they work and know it's all under test so it's truly running and verified.

Here are all the different routes (to show different edge cases I found building this)

``` js
Router.map(function() {
    this.route("add", {path: "/"});
    this.route("dry", {path: "/dry"});
    this.route("edit", {path: "/edit"});
    this.route("success", {path: "/success"});
    this.route("multi", {path: "/multi"});
    this.route("many", {path: "/many"});
    this.route("other", {path: "/other"});
    this.route("hash", {path: "/hash"});
    this.route("edits", {path: "/edits"});
});
```
