### ISSUE TITLE
Can I use Ember Data?

### ISSUE THREAD

**Issue by tehmaestro** [toranb/ember-cli-simple-validation#4]
I just found this plugin and it seems really cool. I'm pretty tied in with Ember Data right now, so is ember-cli-simple-store mandatory?

 Thanks.

**Comment by toranb** [comment]
Good question - we could add ember-data support if ...

```
1) it supports dirty checking at the field level
2) if the above is true - how do you ask if the attr "firstName" is dirty w/ ember-data today?
```

**here is the only line of code that is ember-cli-simple-store dependent that I can think of

https://github.com/toranb/ember-cli-simple-validation/blob/master/addon/components/validation-error-field.js#L24

**Comment by tehmaestro** [comment]
Maybe this can be used?
http://emberjs.com/api/data/classes/DS.Model.html#property_isDirty

So the only difference would be a "dot" ... ?
`Ember.Binding.from("model.%@.IsDirty".fmt(field)).to("isDirty").connect(this);`

EDIT: Sorry, I just saw this is not at individual attribute level. But I guess I could add `isDirty` properties to models + observers , something like:

```
export default DS.Model.extend({
   name: DS.attr("string")
   nameIsDirty: false,
   nameChanged: function() {
     this.set("nameIsDirty", true);
   }.observe("name") 
})
```

**Comment by toranb** [comment]
Ah yes! Give that a shot and report back :)

As I'm not an ember-data user myself I'd love any input on how this works/ if this works. If it does let me know what's required so I can put something in the official README about ember-data support

**Comment by tehmaestro** [comment]
Ok, it works. You can use `DS.Model` or `Ember.Object` too:

```
  Ember.Object.extend({
            username: null,
            usernameIsDirty: false,
            usernameChanged: function () {
                this.set('usernameIsDirty', true);
            }.observes("username")
        });
```

And in template:

```
        {{input
            class="form-control"
            id='username'
            placeholder='Username'
            value=model.username
        }}
   {{#validation-error-field 
           submitted=submitted 
           field="username" 
           model=model 
           validation=usernameValidation
   }}
```

**Comment by toranb** [comment]
Just an update - if you pull down v1.0.0 the field you need to add looks something like the below (not using isDirty anymore)

``` js

  Ember.Object.extend({
            username: null,
            usernameIsPrimed: false,
            usernameChanged: function () {
                this.set('usernameIsPrimed', true);
            }.observes("username")
        });
```
