### ISSUE TITLE
ValidationErrorField hard codes model bindings

### ISSUE THREAD

**Issue by ZebraFlesh** [toranb/ember-cli-simple-validation#6]
The ValidationErrorField component hard codes the bindings to `"model." + field`.  However, if in your route's model hook you're returning an RSVP.hash like so:

``` javascript
model: function () {
  return Ember.RSVP.hash({
    foo: this.store.find('foo'),
    bar: this.store.find('bar')
  });
}
```

then in your template you're going to specify:

``` handlebars
{{#validation-error-field model=model.foo ... }}You need to fill this out!{{/validation-error-field}}
```

At this point, I don't think the bindings will work due to how they're initialized. Seems like they should be initialized with the bound model value.

**Comment by toranb** [comment]
Funny enough the RSVP stuff was just added to the test suite for this very reason :)

Here is the commit that shows all the moving pieces/test code in more detail

https://github.com/toranb/ember-cli-simple-validation/commit/e489b40afbd84bba9599b3c830d97c66c7bf2ead

But in short -your example would work like this

``` js
model: function () {
  return Ember.RSVP.hash({
    foo: this.store.find('foo'),
    bar: this.store.find('bar')
  });
}
```

``` js
export default Ember.Controller.extend(ValidationMixin, {
    nameValidation: validate("model.foo.name")
});
```

``` js
{{input value=model.foo.name placeholder="name"}}
{{#validation-error-field field="foo.name" model=model validation=nameValidation submitted=submitted}}invalid name{{/validation-error-field}}
```

**Comment by toranb** [comment]
I have both the add and edit examples for RSVP in the acceptance tests but if you find something else that would be a good example (for others who follow this convo) please include it here :)

Thanks for the feedback!

**Comment by ZebraFlesh** [comment]
Ah I see my error now: I was interpreting "field" as "form field" (AKA DOM element), but it's actually "model field". Thanks for clearing up my confusion!

**Comment by toranb** [comment]
Awesome! Glad the addon is adding value for others :)
