### ISSUE TITLE
validation-error-field refactoring

### ISSUE THREAD

**Issue by lessless** [toranb/ember-cli-simple-validation#9]
Hello Toran,

obviously error field is different from project to project and provided component can be a great foundation to start in development of the project specific component.
Right now, validation itself  is coupled with the styling logics inside `visible` property of the component what makes it unconvenient to use. What do you think about breaking this functionality in two separate properties, so that there would be a property that answer only one single question - is property valid or not?

**Comment by toranb** [comment]
I'm always open to suggestions that make it more extensible - could we provide a sensible default for those who just want to take what works today/not modify it?

One of the reasons I kept it so bare bones was that you could just add a "hidden" css class and write your own html (keeping the overhead of this library small). My only fear is adding to much configuration/escape valves might increase what you need to know in order to use this library (easily).

**Comment by lessless** [comment]
Ideally, the modification shouldn't be even noticed by the developers who are using library right now. 

Let's take a zurb foundation input styling for example (http://foundation.zurb.com/docs/components/forms.html): 

```html
<div class="large-6 columns">
    <label class="error">Error
       <input type="text" class="error" />
    </label>
    <small class="error">Invalid entry</small>
 </div>
```
ideally, by crossing it with simple validation one want to get something like that: 
```handlebars
{{form-input value=model.zipcode submitted=submitted field="zipcode" model=model validation=zipcodeValidation}}
```
or even

**Comment by lessless** [comment]
Ideally, the modification shouldn't be even noticed by the developers who are using library right now. 

Let's take a zurb foundation input styling for example (http://foundation.zurb.com/docs/components/forms.html): 

``` html
<div class="large-6 columns">
    <label class="error">Error
       <input type="text" class="error" />
    </label>
    <small class="error">Invalid entry</small>
 </div>
```

than, by crossing it with simple validation one want to get something like that: 

``` handlebars
{{form-input value=model.zipcode submitted=submitted field="zipcode" model=model validation=zipcodeValidation}}
```

or even something with DAU, because of starting from Ember 2.1 there will be only one way data binding by default

``` handlebars
{{form-input value=model.zipcode submitted=submitted field="zipcode" validation=zipcodeValidation action='updateProperty'}}
```

and component for that might be something like that:

``` handlebars
{{!-- form-input/template.hbs --}}
<label  for="{{inputElementId}}">{{labelText}}</label>
{{input id=inputElementId value=value placeholder=inputPlaceholder}}
{{#unless isValid}}
  <small class="error">{{errorMessage}}</small>
{{/unless}}
```

``` javascript
import Ember from 'ember';
import ValidationErrorField from 'ember-cli-simple-validation/components/validation-error-field';

export default ValidationErrorField.extend({
  tagName: 'div',
  attributeBindings: ['classNames'],
  classNameBindings: ['isValid::error'],
  //... code for inputElementId, labelTest and errorMessage is omitted because of it's not relevant
});
```

extend component block-element from  inline-element component is upside-down in some way of course .

the only modification needed to incorporate such extension possibility, as far as I can see, is breaking visible property into two properties: `isValid` and `visible`, so that `visible`  observers an `isValid` and set desired class name basing on its value. Actually the `visible` code can be dropped from the component because of it's kinda too specific, imo.  

this is how I did that in my current project and I do not know whether can this experience be generalized or not, but feels good on the surface. 

current validation logic use lots of values and two use-cases so it took some time to crack and I'm still not sure about behavior in all the possible cases.

_p.s._ actually there can be a bare-bones skeleton component as base for the extension and `validation-error-field` can just be an example of such kind of extension

**Comment by toranb** [comment]
@lessless wow that is some legit feedback my friend :)

In complete honesty I'd almost need you /someone with your motivation to champion the effort as I don't yet need this on client work/ commercial apps I'm shipping today. That's not to say I'm against the idea/wouldn't accept a PR.

Thanks for the writeup - if nothing else we could leave this issue open for a bit / see if others want to pick it up. The only strong opinion I had writing this was that I didn't want to turn into easy form (ie- a component that would wrap the html/generate the form for you). If nothing else maybe this change could make it extensible enough that others _could_ built that on top of the core validation component.

**Comment by toranb** [comment]
Closing until someone decides to champion this :)
